blank_issues_enabled: false
contact_links:
  - name: I have a question or problem
    url: https://stalw.art/docs/
    about: Read the documentation, use the search bar to find answers to your questions.
  - name: I have a question or problem not covered in the documentation
    url: https://github.com/stalwartlabs/stalwart/discussions/new?category=q-a
    about: Open a Q&A discussion
  - name: Join Stalwart's Reddit
    url: https://www.reddit.com/r/stalwartlabs
    about: Join our subreddit for help, discussions and release announcements.
  - name: Join Stalwart's Discord
    url: https://discord.com/servers/stalwart-923615863037390889
    about: Join our Discord server for help, discussions and release announcements.
